---
- hosts: all
  become: true
  vars:
    - pri_domain_name: 'test.vagrant.local'
  roles:
  tasks:
    - name: pre-reqs
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
      when: >
            (ansible_os_family == "RedHat" and
            ansible_distribution == "Fedora")

    - name: pre-reqs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
      when: >
            (ansible_os_family == "RedHat" and
            ansible_distribution != "Fedora")

    - name: updating /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
        line: "{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
        state: present
      with_items: groups['all']

- hosts: master-nodes
  become: true
  vars:
    - apache2_install_php: true
    - config_soa_edit_api: true
    - create_pdns_records: false   #defines if dns records should be created/updated
    - create_pdns_zones: false  #defines if dns zones should be created...pdns_fwd_zones and pdns_fwd_zones
    - enable_pdns_recursive_lookups: false
    - enable_pdns_web_server: true
    - install_pdns_recursor: false
    - pdns_fwd_zones:
        - 'prod.vagrant.local'
        - 'test.vagrant.local'
        - 'vagrant.local'
    - pdns_nameservers:  #define nameservers to use when creating zones..
        - '192.168.202.200'
        - '192.168.202.201'
        - '192.168.202.202'
    - pdns_master: true
    - pdns_records:  #define DNS records to create/update...to keep this file small...define in group_vars/all/pdns_records.yml or other...
        - name: vcsa
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.40
          disabled: false
          ttl: 3600
          priority: 0
        - name: vcenter
          zone: "{{ pri_domain_name }}"
          type: CNAME
          changetype: REPLACE
          content: "vcsa.{{ pri_domain_name }}"
          disabled: false
          ttl: 3600
          priority: 0
        - name: test10
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.140
          disabled: false
          ttl: 3600
          priority: 0
        - name: test11
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.141
          disabled: false
          ttl: 3600
          priority: 0
        - name: test12
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.142
          disabled: false
          ttl: 3600
          priority: 0
        - name: test13
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.143
          disabled: false
          ttl: 3600
          priority: 0
        - name: test14
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.144
          disabled: false
          ttl: 3600
          priority: 0
        - name: test15
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.145
          disabled: false
          ttl: 3600
          priority: 0
        - name: test16
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.146
          disabled: false
          ttl: 3600
          priority: 0
        - name: test17
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.147
          disabled: false
          ttl: 3600
          priority: 0
        - name: test18
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.148
          disabled: false
          ttl: 3600
          priority: 0
        - name: test19
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.149
          disabled: false
          ttl: 3600
          priority: 0
        - name: test20
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.150
          disabled: false
          ttl: 3600
          priority: 0
        - name: test21
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.151
          disabled: false
          ttl: 3600
          priority: 0
        - name: test22
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.152
          disabled: false
          ttl: 3600
          priority: 0
        - name: test23
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.153
          disabled: false
          ttl: 3600
          priority: 0
        - name: test24
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.154
          disabled: false
          ttl: 3600
          priority: 0
        - name: test25
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.155
          disabled: false
          ttl: 3600
          priority: 0
        - name: test26
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.156
          disabled: false
          ttl: 3600
          priority: 0
        - name: test27
          zone: "{{ pri_domain_name }}"
          type: A
          changetype: REPLACE
          content: 192.168.202.157
          disabled: false
          ttl: 3600
          priority: 0
    - pdns_rev_zones:
        - '128.28.172.in-addr.arpa'
        - '202.168.192.in-addr.arpa'
    - pdns_slave: false
    - pdns_slaves:
        - '192.168.202.201/32'
        - '192.168.202.202/32'
    - pdns_zone_types: Master
    - phpipam_define_cron_jobs: true
    - pri_domain_name: 'test.vagrant.local'
  roles:
    - role: ansible-apache2
    - role: ansible-mysql
    - role: ansible-powerdns
    - role: ansible-phpipam
  tasks:

- hosts: slave-nodes
  become: true
  vars:
    - apache2_install_php: true
    - create_pdns_records: false   #defines if dns records should be created/updated
    - create_pdns_zones: false  #defines if dns zones should be created...pdns_fwd_zones and pdns_fwd_zones
    - enable_pdns_recursive_lookups: false
    - enable_pdns_web_server: true
    - install_pdns_recursor: false
    - pdns_fwd_zones:
        - 'prod.vagrant.local'
        - 'test.vagrant.local'
        - 'vagrant.local'
    - pdns_master: false
    - pdns_nameservers:  #define nameservers to use when creating zones..
        - '192.168.202.200'
    - pdns_rev_zones:
        - '128.28.172.in-addr.arpa'
        - '202.168.192.in-addr.arpa'
    - pdns_slave: true
    - pdns_zone_types: Slave
    - pri_domain_name: 'test.vagrant.local'
  roles:
    - role: ansible-apache2
    - role: ansible-mysql
    - role: ansible-powerdns
  tasks:
